services:
  app:
    build:
      context: .
    ports:
      - '4000:4000'
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres:15.2
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - '5439:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
